### ISSUE TITLE
Payment system is not fully specified!

### ISSUE THREAD

**Issue by roskee** [adwaTech/project-capstone#29]
I think there are two ways we can implement our online payment system.
1. The first one is by making third party transactions to our client Bank APIs for every payment made by either a bidder or an auctioneer
2. The other way to do it is to keep a digital money balance for each of our customers, have them deposit money by providing an interface for real money transaction from Bank APIs to our system account and incrementing their digital balance according to the deposit transactions they made, create an interface for customers to withdraw their balance to their actual bank account and decrementing their digital balance accordingly. Using this method, we are required to make an actual transaction at a time of deposit and withdraw operations only.
In my opinion the 2nd method is much better, flexible and efficient.

**Comment by mesi473** [comment]
The second one is much better so i prefer the second one
